export type TimezoneOption = { value: string; label: string };

// Curated representative zones: one familiar location per common offset, excluding Africa.
export const TIMEZONE_OPTIONS: TimezoneOption[] = [
  { value: "Pacific/Honolulu", label: "GMT-10:00 — Honolulu, United States" },
  { value: "America/Anchorage", label: "GMT-9:00 — Anchorage, United States" },
  { value: "America/Los_Angeles", label: "GMT-8:00 — Los Angeles, United States" },
  { value: "America/Denver", label: "GMT-7:00 — Denver, United States" },
  { value: "America/Chicago", label: "GMT-6:00 — Chicago, United States" },
  { value: "America/New_York", label: "GMT-5:00 — New York, United States" },
  { value: "America/Halifax", label: "GMT-4:00 — Halifax, Canada" },
  { value: "America/Argentina/Buenos_Aires", label: "GMT-3:00 — Buenos Aires, Argentina" },
  { value: "Atlantic/Azores", label: "GMT-1:00 — Azores, Portugal" },
  { value: "Europe/London", label: "GMT+0:00 — London, United Kingdom" },
  { value: "Europe/Paris", label: "GMT+1:00 — Paris, France" },
  { value: "Europe/Athens", label: "GMT+2:00 — Athens, Greece" },
  { value: "Asia/Riyadh", label: "GMT+3:00 — Riyadh, Saudi Arabia" },
  { value: "Asia/Dubai", label: "GMT+4:00 — Dubai, United Arab Emirates" },
  { value: "Asia/Karachi", label: "GMT+5:00 — Karachi, Pakistan" },
  { value: "Asia/Kolkata", label: "GMT+5:30 — New Delhi, India" },
  { value: "Asia/Kathmandu", label: "GMT+5:45 — Kathmandu, Nepal" },
  { value: "Asia/Dhaka", label: "GMT+6:00 — Dhaka, Bangladesh" },
  { value: "Asia/Bangkok", label: "GMT+7:00 — Bangkok, Thailand" },
  { value: "Asia/Singapore", label: "GMT+8:00 — Singapore" },
  { value: "Asia/Tokyo", label: "GMT+9:00 — Tokyo, Japan" },
  { value: "Australia/Adelaide", label: "GMT+9:30 — Adelaide, Australia" },
  { value: "Australia/Sydney", label: "GMT+10:00 — Sydney, Australia" },
  { value: "Pacific/Noumea", label: "GMT+11:00 — Nouméa, New Caledonia" },
  { value: "Pacific/Auckland", label: "GMT+12:00 — Auckland, New Zealand" },
  { value: "Pacific/Apia", label: "GMT+13:00 — Apia, Samoa" },
  { value: "Pacific/Kiritimati", label: "GMT+14:00 — Kiritimati, Kiribati" },
];
