/* Generated from the system IANA zone.tab database. */
export type TimezoneOption = { value: string; countryCodes: string; location: string };

export const GLOBAL_TIMEZONES: TimezoneOption[] = [
  { value: 'Africa/Abidjan', countryCodes: 'CI', location: 'Abidjan' },
  { value: 'Africa/Accra', countryCodes: 'GH', location: 'Accra' },
  { value: 'Africa/Addis_Ababa', countryCodes: 'ET', location: 'Addis Ababa' },
  { value: 'Africa/Algiers', countryCodes: 'DZ', location: 'Algiers' },
  { value: 'Africa/Asmara', countryCodes: 'ER', location: 'Asmara' },
  { value: 'Africa/Bamako', countryCodes: 'ML', location: 'Bamako' },
  { value: 'Africa/Bangui', countryCodes: 'CF', location: 'Bangui' },
  { value: 'Africa/Banjul', countryCodes: 'GM', location: 'Banjul' },
  { value: 'Africa/Bissau', countryCodes: 'GW', location: 'Bissau' },
  { value: 'Africa/Blantyre', countryCodes: 'MW', location: 'Blantyre' },
  { value: 'Africa/Brazzaville', countryCodes: 'CG', location: 'Brazzaville' },
  { value: 'Africa/Bujumbura', countryCodes: 'BI', location: 'Bujumbura' },
  { value: 'Africa/Cairo', countryCodes: 'EG', location: 'Cairo' },
  { value: 'Africa/Casablanca', countryCodes: 'MA', location: 'Casablanca' },
  { value: 'Africa/Ceuta', countryCodes: 'ES', location: 'Ceuta' },
  { value: 'Africa/Conakry', countryCodes: 'GN', location: 'Conakry' },
  { value: 'Africa/Dakar', countryCodes: 'SN', location: 'Dakar' },
  { value: 'Africa/Dar_es_Salaam', countryCodes: 'TZ', location: 'Dar es Salaam' },
  { value: 'Africa/Djibouti', countryCodes: 'DJ', location: 'Djibouti' },
  { value: 'Africa/Douala', countryCodes: 'CM', location: 'Douala' },
  { value: 'Africa/El_Aaiun', countryCodes: 'EH', location: 'El Aaiun' },
  { value: 'Africa/Freetown', countryCodes: 'SL', location: 'Freetown' },
  { value: 'Africa/Gaborone', countryCodes: 'BW', location: 'Gaborone' },
  { value: 'Africa/Harare', countryCodes: 'ZW', location: 'Harare' },
  { value: 'Africa/Johannesburg', countryCodes: 'ZA', location: 'Johannesburg' },
  { value: 'Africa/Juba', countryCodes: 'SS', location: 'Juba' },
  { value: 'Africa/Kampala', countryCodes: 'UG', location: 'Kampala' },
  { value: 'Africa/Khartoum', countryCodes: 'SD', location: 'Khartoum' },
  { value: 'Africa/Kigali', countryCodes: 'RW', location: 'Kigali' },
  { value: 'Africa/Kinshasa', countryCodes: 'CD', location: 'Kinshasa' },
  { value: 'Africa/Lagos', countryCodes: 'NG', location: 'Lagos' },
  { value: 'Africa/Libreville', countryCodes: 'GA', location: 'Libreville' },
  { value: 'Africa/Lome', countryCodes: 'TG', location: 'Lome' },
  { value: 'Africa/Luanda', countryCodes: 'AO', location: 'Luanda' },
  { value: 'Africa/Lubumbashi', countryCodes: 'CD', location: 'Lubumbashi' },
  { value: 'Africa/Lusaka', countryCodes: 'ZM', location: 'Lusaka' },
  { value: 'Africa/Malabo', countryCodes: 'GQ', location: 'Malabo' },
  { value: 'Africa/Maputo', countryCodes: 'MZ', location: 'Maputo' },
  { value: 'Africa/Maseru', countryCodes: 'LS', location: 'Maseru' },
  { value: 'Africa/Mbabane', countryCodes: 'SZ', location: 'Mbabane' },
  { value: 'Africa/Mogadishu', countryCodes: 'SO', location: 'Mogadishu' },
  { value: 'Africa/Monrovia', countryCodes: 'LR', location: 'Monrovia' },
  { value: 'Africa/Nairobi', countryCodes: 'KE', location: 'Nairobi' },
  { value: 'Africa/Ndjamena', countryCodes: 'TD', location: 'Ndjamena' },
  { value: 'Africa/Niamey', countryCodes: 'NE', location: 'Niamey' },
  { value: 'Africa/Nouakchott', countryCodes: 'MR', location: 'Nouakchott' },
  { value: 'Africa/Ouagadougou', countryCodes: 'BF', location: 'Ouagadougou' },
  { value: 'Africa/Porto-Novo', countryCodes: 'BJ', location: 'Porto-Novo' },
  { value: 'Africa/Sao_Tome', countryCodes: 'ST', location: 'Sao Tome' },
  { value: 'Africa/Tripoli', countryCodes: 'LY', location: 'Tripoli' },
  { value: 'Africa/Tunis', countryCodes: 'TN', location: 'Tunis' },
  { value: 'Africa/Windhoek', countryCodes: 'NA', location: 'Windhoek' },
  { value: 'America/Adak', countryCodes: 'US', location: 'Adak' },
  { value: 'America/Anchorage', countryCodes: 'US', location: 'Anchorage' },
  { value: 'America/Anguilla', countryCodes: 'AI', location: 'Anguilla' },
  { value: 'America/Antigua', countryCodes: 'AG', location: 'Antigua' },
  { value: 'America/Araguaina', countryCodes: 'BR', location: 'Araguaina' },
  { value: 'America/Argentina/Buenos_Aires', countryCodes: 'AR', location: 'Argentina / Buenos Aires' },
  { value: 'America/Argentina/Catamarca', countryCodes: 'AR', location: 'Argentina / Catamarca' },
  { value: 'America/Argentina/Cordoba', countryCodes: 'AR', location: 'Argentina / Cordoba' },
  { value: 'America/Argentina/Jujuy', countryCodes: 'AR', location: 'Argentina / Jujuy' },
  { value: 'America/Argentina/La_Rioja', countryCodes: 'AR', location: 'Argentina / La Rioja' },
  { value: 'America/Argentina/Mendoza', countryCodes: 'AR', location: 'Argentina / Mendoza' },
  { value: 'America/Argentina/Rio_Gallegos', countryCodes: 'AR', location: 'Argentina / Rio Gallegos' },
  { value: 'America/Argentina/Salta', countryCodes: 'AR', location: 'Argentina / Salta' },
  { value: 'America/Argentina/San_Juan', countryCodes: 'AR', location: 'Argentina / San Juan' },
  { value: 'America/Argentina/San_Luis', countryCodes: 'AR', location: 'Argentina / San Luis' },
  { value: 'America/Argentina/Tucuman', countryCodes: 'AR', location: 'Argentina / Tucuman' },
  { value: 'America/Argentina/Ushuaia', countryCodes: 'AR', location: 'Argentina / Ushuaia' },
  { value: 'America/Aruba', countryCodes: 'AW', location: 'Aruba' },
  { value: 'America/Asuncion', countryCodes: 'PY', location: 'Asuncion' },
  { value: 'America/Atikokan', countryCodes: 'CA', location: 'Atikokan' },
  { value: 'America/Bahia', countryCodes: 'BR', location: 'Bahia' },
  { value: 'America/Bahia_Banderas', countryCodes: 'MX', location: 'Bahia Banderas' },
  { value: 'America/Barbados', countryCodes: 'BB', location: 'Barbados' },
  { value: 'America/Belem', countryCodes: 'BR', location: 'Belem' },
  { value: 'America/Belize', countryCodes: 'BZ', location: 'Belize' },
  { value: 'America/Blanc-Sablon', countryCodes: 'CA', location: 'Blanc-Sablon' },
  { value: 'America/Boa_Vista', countryCodes: 'BR', location: 'Boa Vista' },
  { value: 'America/Bogota', countryCodes: 'CO', location: 'Bogota' },
  { value: 'America/Boise', countryCodes: 'US', location: 'Boise' },
  { value: 'America/Cambridge_Bay', countryCodes: 'CA', location: 'Cambridge Bay' },
  { value: 'America/Campo_Grande', countryCodes: 'BR', location: 'Campo Grande' },
  { value: 'America/Cancun', countryCodes: 'MX', location: 'Cancun' },
  { value: 'America/Caracas', countryCodes: 'VE', location: 'Caracas' },
  { value: 'America/Cayenne', countryCodes: 'GF', location: 'Cayenne' },
  { value: 'America/Cayman', countryCodes: 'KY', location: 'Cayman' },
  { value: 'America/Chicago', countryCodes: 'US', location: 'Chicago' },
  { value: 'America/Chihuahua', countryCodes: 'MX', location: 'Chihuahua' },
  { value: 'America/Ciudad_Juarez', countryCodes: 'MX', location: 'Ciudad Juarez' },
  { value: 'America/Costa_Rica', countryCodes: 'CR', location: 'Costa Rica' },
  { value: 'America/Coyhaique', countryCodes: 'CL', location: 'Coyhaique' },
  { value: 'America/Creston', countryCodes: 'CA', location: 'Creston' },
  { value: 'America/Cuiaba', countryCodes: 'BR', location: 'Cuiaba' },
  { value: 'America/Curacao', countryCodes: 'CW', location: 'Curacao' },
  { value: 'America/Danmarkshavn', countryCodes: 'GL', location: 'Danmarkshavn' },
  { value: 'America/Dawson', countryCodes: 'CA', location: 'Dawson' },
  { value: 'America/Dawson_Creek', countryCodes: 'CA', location: 'Dawson Creek' },
  { value: 'America/Denver', countryCodes: 'US', location: 'Denver' },
  { value: 'America/Detroit', countryCodes: 'US', location: 'Detroit' },
  { value: 'America/Dominica', countryCodes: 'DM', location: 'Dominica' },
  { value: 'America/Edmonton', countryCodes: 'CA', location: 'Edmonton' },
  { value: 'America/Eirunepe', countryCodes: 'BR', location: 'Eirunepe' },
  { value: 'America/El_Salvador', countryCodes: 'SV', location: 'El Salvador' },
  { value: 'America/Fort_Nelson', countryCodes: 'CA', location: 'Fort Nelson' },
  { value: 'America/Fortaleza', countryCodes: 'BR', location: 'Fortaleza' },
  { value: 'America/Glace_Bay', countryCodes: 'CA', location: 'Glace Bay' },
  { value: 'America/Goose_Bay', countryCodes: 'CA', location: 'Goose Bay' },
  { value: 'America/Grand_Turk', countryCodes: 'TC', location: 'Grand Turk' },
  { value: 'America/Grenada', countryCodes: 'GD', location: 'Grenada' },
  { value: 'America/Guadeloupe', countryCodes: 'GP', location: 'Guadeloupe' },
  { value: 'America/Guatemala', countryCodes: 'GT', location: 'Guatemala' },
  { value: 'America/Guayaquil', countryCodes: 'EC', location: 'Guayaquil' },
  { value: 'America/Guyana', countryCodes: 'GY', location: 'Guyana' },
  { value: 'America/Halifax', countryCodes: 'CA', location: 'Halifax' },
  { value: 'America/Havana', countryCodes: 'CU', location: 'Havana' },
  { value: 'America/Hermosillo', countryCodes: 'MX', location: 'Hermosillo' },
  { value: 'America/Indiana/Indianapolis', countryCodes: 'US', location: 'Indiana / Indianapolis' },
  { value: 'America/Indiana/Knox', countryCodes: 'US', location: 'Indiana / Knox' },
  { value: 'America/Indiana/Marengo', countryCodes: 'US', location: 'Indiana / Marengo' },
  { value: 'America/Indiana/Petersburg', countryCodes: 'US', location: 'Indiana / Petersburg' },
  { value: 'America/Indiana/Tell_City', countryCodes: 'US', location: 'Indiana / Tell City' },
  { value: 'America/Indiana/Vevay', countryCodes: 'US', location: 'Indiana / Vevay' },
  { value: 'America/Indiana/Vincennes', countryCodes: 'US', location: 'Indiana / Vincennes' },
  { value: 'America/Indiana/Winamac', countryCodes: 'US', location: 'Indiana / Winamac' },
  { value: 'America/Inuvik', countryCodes: 'CA', location: 'Inuvik' },
  { value: 'America/Iqaluit', countryCodes: 'CA', location: 'Iqaluit' },
  { value: 'America/Jamaica', countryCodes: 'JM', location: 'Jamaica' },
  { value: 'America/Juneau', countryCodes: 'US', location: 'Juneau' },
  { value: 'America/Kentucky/Louisville', countryCodes: 'US', location: 'Kentucky / Louisville' },
  { value: 'America/Kentucky/Monticello', countryCodes: 'US', location: 'Kentucky / Monticello' },
  { value: 'America/Kralendijk', countryCodes: 'BQ', location: 'Kralendijk' },
  { value: 'America/La_Paz', countryCodes: 'BO', location: 'La Paz' },
  { value: 'America/Lima', countryCodes: 'PE', location: 'Lima' },
  { value: 'America/Los_Angeles', countryCodes: 'US', location: 'Los Angeles' },
  { value: 'America/Lower_Princes', countryCodes: 'SX', location: 'Lower Princes' },
  { value: 'America/Maceio', countryCodes: 'BR', location: 'Maceio' },
  { value: 'America/Managua', countryCodes: 'NI', location: 'Managua' },
  { value: 'America/Manaus', countryCodes: 'BR', location: 'Manaus' },
  { value: 'America/Marigot', countryCodes: 'MF', location: 'Marigot' },
  { value: 'America/Martinique', countryCodes: 'MQ', location: 'Martinique' },
  { value: 'America/Matamoros', countryCodes: 'MX', location: 'Matamoros' },
  { value: 'America/Mazatlan', countryCodes: 'MX', location: 'Mazatlan' },
  { value: 'America/Menominee', countryCodes: 'US', location: 'Menominee' },
  { value: 'America/Merida', countryCodes: 'MX', location: 'Merida' },
  { value: 'America/Metlakatla', countryCodes: 'US', location: 'Metlakatla' },
  { value: 'America/Mexico_City', countryCodes: 'MX', location: 'Mexico City' },
  { value: 'America/Miquelon', countryCodes: 'PM', location: 'Miquelon' },
  { value: 'America/Moncton', countryCodes: 'CA', location: 'Moncton' },
  { value: 'America/Monterrey', countryCodes: 'MX', location: 'Monterrey' },
  { value: 'America/Montevideo', countryCodes: 'UY', location: 'Montevideo' },
  { value: 'America/Montserrat', countryCodes: 'MS', location: 'Montserrat' },
  { value: 'America/Nassau', countryCodes: 'BS', location: 'Nassau' },
  { value: 'America/New_York', countryCodes: 'US', location: 'New York' },
  { value: 'America/Nome', countryCodes: 'US', location: 'Nome' },
  { value: 'America/Noronha', countryCodes: 'BR', location: 'Noronha' },
  { value: 'America/North_Dakota/Beulah', countryCodes: 'US', location: 'North Dakota / Beulah' },
  { value: 'America/North_Dakota/Center', countryCodes: 'US', location: 'North Dakota / Center' },
  { value: 'America/North_Dakota/New_Salem', countryCodes: 'US', location: 'North Dakota / New Salem' },
  { value: 'America/Nuuk', countryCodes: 'GL', location: 'Nuuk' },
  { value: 'America/Ojinaga', countryCodes: 'MX', location: 'Ojinaga' },
  { value: 'America/Panama', countryCodes: 'PA', location: 'Panama' },
  { value: 'America/Paramaribo', countryCodes: 'SR', location: 'Paramaribo' },
  { value: 'America/Phoenix', countryCodes: 'US', location: 'Phoenix' },
  { value: 'America/Port-au-Prince', countryCodes: 'HT', location: 'Port-au-Prince' },
  { value: 'America/Port_of_Spain', countryCodes: 'TT', location: 'Port of Spain' },
  { value: 'America/Porto_Velho', countryCodes: 'BR', location: 'Porto Velho' },
  { value: 'America/Puerto_Rico', countryCodes: 'PR', location: 'Puerto Rico' },
  { value: 'America/Punta_Arenas', countryCodes: 'CL', location: 'Punta Arenas' },
  { value: 'America/Rankin_Inlet', countryCodes: 'CA', location: 'Rankin Inlet' },
  { value: 'America/Recife', countryCodes: 'BR', location: 'Recife' },
  { value: 'America/Regina', countryCodes: 'CA', location: 'Regina' },
  { value: 'America/Resolute', countryCodes: 'CA', location: 'Resolute' },
  { value: 'America/Rio_Branco', countryCodes: 'BR', location: 'Rio Branco' },
  { value: 'America/Santarem', countryCodes: 'BR', location: 'Santarem' },
  { value: 'America/Santiago', countryCodes: 'CL', location: 'Santiago' },
  { value: 'America/Santo_Domingo', countryCodes: 'DO', location: 'Santo Domingo' },
  { value: 'America/Sao_Paulo', countryCodes: 'BR', location: 'Sao Paulo' },
  { value: 'America/Scoresbysund', countryCodes: 'GL', location: 'Scoresbysund' },
  { value: 'America/Sitka', countryCodes: 'US', location: 'Sitka' },
  { value: 'America/St_Barthelemy', countryCodes: 'BL', location: 'St Barthelemy' },
  { value: 'America/St_Johns', countryCodes: 'CA', location: 'St Johns' },
  { value: 'America/St_Kitts', countryCodes: 'KN', location: 'St Kitts' },
  { value: 'America/St_Lucia', countryCodes: 'LC', location: 'St Lucia' },
  { value: 'America/St_Thomas', countryCodes: 'VI', location: 'St Thomas' },
  { value: 'America/St_Vincent', countryCodes: 'VC', location: 'St Vincent' },
  { value: 'America/Swift_Current', countryCodes: 'CA', location: 'Swift Current' },
  { value: 'America/Tegucigalpa', countryCodes: 'HN', location: 'Tegucigalpa' },
  { value: 'America/Thule', countryCodes: 'GL', location: 'Thule' },
  { value: 'America/Tijuana', countryCodes: 'MX', location: 'Tijuana' },
  { value: 'America/Toronto', countryCodes: 'CA', location: 'Toronto' },
  { value: 'America/Tortola', countryCodes: 'VG', location: 'Tortola' },
  { value: 'America/Vancouver', countryCodes: 'CA', location: 'Vancouver' },
  { value: 'America/Whitehorse', countryCodes: 'CA', location: 'Whitehorse' },
  { value: 'America/Winnipeg', countryCodes: 'CA', location: 'Winnipeg' },
  { value: 'America/Yakutat', countryCodes: 'US', location: 'Yakutat' },
  { value: 'Antarctica/Casey', countryCodes: 'AQ', location: 'Casey' },
  { value: 'Antarctica/Davis', countryCodes: 'AQ', location: 'Davis' },
  { value: 'Antarctica/DumontDUrville', countryCodes: 'AQ', location: 'DumontDUrville' },
  { value: 'Antarctica/Macquarie', countryCodes: 'AU', location: 'Macquarie' },
  { value: 'Antarctica/Mawson', countryCodes: 'AQ', location: 'Mawson' },
  { value: 'Antarctica/McMurdo', countryCodes: 'AQ', location: 'McMurdo' },
  { value: 'Antarctica/Palmer', countryCodes: 'AQ', location: 'Palmer' },
  { value: 'Antarctica/Rothera', countryCodes: 'AQ', location: 'Rothera' },
  { value: 'Antarctica/Syowa', countryCodes: 'AQ', location: 'Syowa' },
  { value: 'Antarctica/Troll', countryCodes: 'AQ', location: 'Troll' },
  { value: 'Antarctica/Vostok', countryCodes: 'AQ', location: 'Vostok' },
  { value: 'Arctic/Longyearbyen', countryCodes: 'SJ', location: 'Longyearbyen' },
  { value: 'Asia/Aden', countryCodes: 'YE', location: 'Aden' },
  { value: 'Asia/Almaty', countryCodes: 'KZ', location: 'Almaty' },
  { value: 'Asia/Amman', countryCodes: 'JO', location: 'Amman' },
  { value: 'Asia/Anadyr', countryCodes: 'RU', location: 'Anadyr' },
  { value: 'Asia/Aqtau', countryCodes: 'KZ', location: 'Aqtau' },
  { value: 'Asia/Aqtobe', countryCodes: 'KZ', location: 'Aqtobe' },
  { value: 'Asia/Ashgabat', countryCodes: 'TM', location: 'Ashgabat' },
  { value: 'Asia/Atyrau', countryCodes: 'KZ', location: 'Atyrau' },
  { value: 'Asia/Baghdad', countryCodes: 'IQ', location: 'Baghdad' },
  { value: 'Asia/Bahrain', countryCodes: 'BH', location: 'Bahrain' },
  { value: 'Asia/Baku', countryCodes: 'AZ', location: 'Baku' },
  { value: 'Asia/Bangkok', countryCodes: 'TH', location: 'Bangkok' },
  { value: 'Asia/Barnaul', countryCodes: 'RU', location: 'Barnaul' },
  { value: 'Asia/Beirut', countryCodes: 'LB', location: 'Beirut' },
  { value: 'Asia/Bishkek', countryCodes: 'KG', location: 'Bishkek' },
  { value: 'Asia/Brunei', countryCodes: 'BN', location: 'Brunei' },
  { value: 'Asia/Chita', countryCodes: 'RU', location: 'Chita' },
  { value: 'Asia/Colombo', countryCodes: 'LK', location: 'Colombo' },
  { value: 'Asia/Damascus', countryCodes: 'SY', location: 'Damascus' },
  { value: 'Asia/Dhaka', countryCodes: 'BD', location: 'Dhaka' },
  { value: 'Asia/Dili', countryCodes: 'TL', location: 'Dili' },
  { value: 'Asia/Dubai', countryCodes: 'AE', location: 'Dubai' },
  { value: 'Asia/Dushanbe', countryCodes: 'TJ', location: 'Dushanbe' },
  { value: 'Asia/Famagusta', countryCodes: 'CY', location: 'Famagusta' },
  { value: 'Asia/Gaza', countryCodes: 'PS', location: 'Gaza' },
  { value: 'Asia/Hebron', countryCodes: 'PS', location: 'Hebron' },
  { value: 'Asia/Ho_Chi_Minh', countryCodes: 'VN', location: 'Ho Chi Minh' },
  { value: 'Asia/Hong_Kong', countryCodes: 'HK', location: 'Hong Kong' },
  { value: 'Asia/Hovd', countryCodes: 'MN', location: 'Hovd' },
  { value: 'Asia/Irkutsk', countryCodes: 'RU', location: 'Irkutsk' },
  { value: 'Asia/Jakarta', countryCodes: 'ID', location: 'Jakarta' },
  { value: 'Asia/Jayapura', countryCodes: 'ID', location: 'Jayapura' },
  { value: 'Asia/Jerusalem', countryCodes: 'IL', location: 'Jerusalem' },
  { value: 'Asia/Kabul', countryCodes: 'AF', location: 'Kabul' },
  { value: 'Asia/Kamchatka', countryCodes: 'RU', location: 'Kamchatka' },
  { value: 'Asia/Karachi', countryCodes: 'PK', location: 'Karachi' },
  { value: 'Asia/Kathmandu', countryCodes: 'NP', location: 'Kathmandu' },
  { value: 'Asia/Khandyga', countryCodes: 'RU', location: 'Khandyga' },
  { value: 'Asia/Kolkata', countryCodes: 'IN', location: 'Kolkata' },
  { value: 'Asia/Krasnoyarsk', countryCodes: 'RU', location: 'Krasnoyarsk' },
  { value: 'Asia/Kuala_Lumpur', countryCodes: 'MY', location: 'Kuala Lumpur' },
  { value: 'Asia/Kuching', countryCodes: 'MY', location: 'Kuching' },
  { value: 'Asia/Kuwait', countryCodes: 'KW', location: 'Kuwait' },
  { value: 'Asia/Macau', countryCodes: 'MO', location: 'Macau' },
  { value: 'Asia/Magadan', countryCodes: 'RU', location: 'Magadan' },
  { value: 'Asia/Makassar', countryCodes: 'ID', location: 'Makassar' },
  { value: 'Asia/Manila', countryCodes: 'PH', location: 'Manila' },
  { value: 'Asia/Muscat', countryCodes: 'OM', location: 'Muscat' },
  { value: 'Asia/Nicosia', countryCodes: 'CY', location: 'Nicosia' },
  { value: 'Asia/Novokuznetsk', countryCodes: 'RU', location: 'Novokuznetsk' },
  { value: 'Asia/Novosibirsk', countryCodes: 'RU', location: 'Novosibirsk' },
  { value: 'Asia/Omsk', countryCodes: 'RU', location: 'Omsk' },
  { value: 'Asia/Oral', countryCodes: 'KZ', location: 'Oral' },
  { value: 'Asia/Phnom_Penh', countryCodes: 'KH', location: 'Phnom Penh' },
  { value: 'Asia/Pontianak', countryCodes: 'ID', location: 'Pontianak' },
  { value: 'Asia/Pyongyang', countryCodes: 'KP', location: 'Pyongyang' },
  { value: 'Asia/Qatar', countryCodes: 'QA', location: 'Qatar' },
  { value: 'Asia/Qostanay', countryCodes: 'KZ', location: 'Qostanay' },
  { value: 'Asia/Qyzylorda', countryCodes: 'KZ', location: 'Qyzylorda' },
  { value: 'Asia/Riyadh', countryCodes: 'SA', location: 'Riyadh' },
  { value: 'Asia/Sakhalin', countryCodes: 'RU', location: 'Sakhalin' },
  { value: 'Asia/Samarkand', countryCodes: 'UZ', location: 'Samarkand' },
  { value: 'Asia/Seoul', countryCodes: 'KR', location: 'Seoul' },
  { value: 'Asia/Shanghai', countryCodes: 'CN', location: 'Shanghai' },
  { value: 'Asia/Singapore', countryCodes: 'SG', location: 'Singapore' },
  { value: 'Asia/Srednekolymsk', countryCodes: 'RU', location: 'Srednekolymsk' },
  { value: 'Asia/Taipei', countryCodes: 'TW', location: 'Taipei' },
  { value: 'Asia/Tashkent', countryCodes: 'UZ', location: 'Tashkent' },
  { value: 'Asia/Tbilisi', countryCodes: 'GE', location: 'Tbilisi' },
  { value: 'Asia/Tehran', countryCodes: 'IR', location: 'Tehran' },
  { value: 'Asia/Thimphu', countryCodes: 'BT', location: 'Thimphu' },
  { value: 'Asia/Tokyo', countryCodes: 'JP', location: 'Tokyo' },
  { value: 'Asia/Tomsk', countryCodes: 'RU', location: 'Tomsk' },
  { value: 'Asia/Ulaanbaatar', countryCodes: 'MN', location: 'Ulaanbaatar' },
  { value: 'Asia/Urumqi', countryCodes: 'CN', location: 'Urumqi' },
  { value: 'Asia/Ust-Nera', countryCodes: 'RU', location: 'Ust-Nera' },
  { value: 'Asia/Vientiane', countryCodes: 'LA', location: 'Vientiane' },
  { value: 'Asia/Vladivostok', countryCodes: 'RU', location: 'Vladivostok' },
  { value: 'Asia/Yakutsk', countryCodes: 'RU', location: 'Yakutsk' },
  { value: 'Asia/Yangon', countryCodes: 'MM', location: 'Yangon' },
  { value: 'Asia/Yekaterinburg', countryCodes: 'RU', location: 'Yekaterinburg' },
  { value: 'Asia/Yerevan', countryCodes: 'AM', location: 'Yerevan' },
  { value: 'Atlantic/Azores', countryCodes: 'PT', location: 'Azores' },
  { value: 'Atlantic/Bermuda', countryCodes: 'BM', location: 'Bermuda' },
  { value: 'Atlantic/Canary', countryCodes: 'ES', location: 'Canary' },
  { value: 'Atlantic/Cape_Verde', countryCodes: 'CV', location: 'Cape Verde' },
  { value: 'Atlantic/Faroe', countryCodes: 'FO', location: 'Faroe' },
  { value: 'Atlantic/Madeira', countryCodes: 'PT', location: 'Madeira' },
  { value: 'Atlantic/Reykjavik', countryCodes: 'IS', location: 'Reykjavik' },
  { value: 'Atlantic/South_Georgia', countryCodes: 'GS', location: 'South Georgia' },
  { value: 'Atlantic/St_Helena', countryCodes: 'SH', location: 'St Helena' },
  { value: 'Atlantic/Stanley', countryCodes: 'FK', location: 'Stanley' },
  { value: 'Australia/Adelaide', countryCodes: 'AU', location: 'Adelaide' },
  { value: 'Australia/Brisbane', countryCodes: 'AU', location: 'Brisbane' },
  { value: 'Australia/Broken_Hill', countryCodes: 'AU', location: 'Broken Hill' },
  { value: 'Australia/Darwin', countryCodes: 'AU', location: 'Darwin' },
  { value: 'Australia/Eucla', countryCodes: 'AU', location: 'Eucla' },
  { value: 'Australia/Hobart', countryCodes: 'AU', location: 'Hobart' },
  { value: 'Australia/Lindeman', countryCodes: 'AU', location: 'Lindeman' },
  { value: 'Australia/Lord_Howe', countryCodes: 'AU', location: 'Lord Howe' },
  { value: 'Australia/Melbourne', countryCodes: 'AU', location: 'Melbourne' },
  { value: 'Australia/Perth', countryCodes: 'AU', location: 'Perth' },
  { value: 'Australia/Sydney', countryCodes: 'AU', location: 'Sydney' },
  { value: 'Europe/Amsterdam', countryCodes: 'NL', location: 'Amsterdam' },
  { value: 'Europe/Andorra', countryCodes: 'AD', location: 'Andorra' },
  { value: 'Europe/Astrakhan', countryCodes: 'RU', location: 'Astrakhan' },
  { value: 'Europe/Athens', countryCodes: 'GR', location: 'Athens' },
  { value: 'Europe/Belgrade', countryCodes: 'RS', location: 'Belgrade' },
  { value: 'Europe/Berlin', countryCodes: 'DE', location: 'Berlin' },
  { value: 'Europe/Bratislava', countryCodes: 'SK', location: 'Bratislava' },
  { value: 'Europe/Brussels', countryCodes: 'BE', location: 'Brussels' },
  { value: 'Europe/Bucharest', countryCodes: 'RO', location: 'Bucharest' },
  { value: 'Europe/Budapest', countryCodes: 'HU', location: 'Budapest' },
  { value: 'Europe/Busingen', countryCodes: 'DE', location: 'Busingen' },
  { value: 'Europe/Chisinau', countryCodes: 'MD', location: 'Chisinau' },
  { value: 'Europe/Copenhagen', countryCodes: 'DK', location: 'Copenhagen' },
  { value: 'Europe/Dublin', countryCodes: 'IE', location: 'Dublin' },
  { value: 'Europe/Gibraltar', countryCodes: 'GI', location: 'Gibraltar' },
  { value: 'Europe/Guernsey', countryCodes: 'GG', location: 'Guernsey' },
  { value: 'Europe/Helsinki', countryCodes: 'FI', location: 'Helsinki' },
  { value: 'Europe/Isle_of_Man', countryCodes: 'IM', location: 'Isle of Man' },
  { value: 'Europe/Istanbul', countryCodes: 'TR', location: 'Istanbul' },
  { value: 'Europe/Jersey', countryCodes: 'JE', location: 'Jersey' },
  { value: 'Europe/Kaliningrad', countryCodes: 'RU', location: 'Kaliningrad' },
  { value: 'Europe/Kirov', countryCodes: 'RU', location: 'Kirov' },
  { value: 'Europe/Kyiv', countryCodes: 'UA', location: 'Kyiv' },
  { value: 'Europe/Lisbon', countryCodes: 'PT', location: 'Lisbon' },
  { value: 'Europe/Ljubljana', countryCodes: 'SI', location: 'Ljubljana' },
  { value: 'Europe/London', countryCodes: 'GB', location: 'London' },
  { value: 'Europe/Luxembourg', countryCodes: 'LU', location: 'Luxembourg' },
  { value: 'Europe/Madrid', countryCodes: 'ES', location: 'Madrid' },
  { value: 'Europe/Malta', countryCodes: 'MT', location: 'Malta' },
  { value: 'Europe/Mariehamn', countryCodes: 'AX', location: 'Mariehamn' },
  { value: 'Europe/Minsk', countryCodes: 'BY', location: 'Minsk' },
  { value: 'Europe/Monaco', countryCodes: 'MC', location: 'Monaco' },
  { value: 'Europe/Moscow', countryCodes: 'RU', location: 'Moscow' },
  { value: 'Europe/Oslo', countryCodes: 'NO', location: 'Oslo' },
  { value: 'Europe/Paris', countryCodes: 'FR', location: 'Paris' },
  { value: 'Europe/Podgorica', countryCodes: 'ME', location: 'Podgorica' },
  { value: 'Europe/Prague', countryCodes: 'CZ', location: 'Prague' },
  { value: 'Europe/Riga', countryCodes: 'LV', location: 'Riga' },
  { value: 'Europe/Rome', countryCodes: 'IT', location: 'Rome' },
  { value: 'Europe/Samara', countryCodes: 'RU', location: 'Samara' },
  { value: 'Europe/San_Marino', countryCodes: 'SM', location: 'San Marino' },
  { value: 'Europe/Sarajevo', countryCodes: 'BA', location: 'Sarajevo' },
  { value: 'Europe/Saratov', countryCodes: 'RU', location: 'Saratov' },
  { value: 'Europe/Simferopol', countryCodes: 'UA', location: 'Simferopol' },
  { value: 'Europe/Skopje', countryCodes: 'MK', location: 'Skopje' },
  { value: 'Europe/Sofia', countryCodes: 'BG', location: 'Sofia' },
  { value: 'Europe/Stockholm', countryCodes: 'SE', location: 'Stockholm' },
  { value: 'Europe/Tallinn', countryCodes: 'EE', location: 'Tallinn' },
  { value: 'Europe/Tirane', countryCodes: 'AL', location: 'Tirane' },
  { value: 'Europe/Ulyanovsk', countryCodes: 'RU', location: 'Ulyanovsk' },
  { value: 'Europe/Vaduz', countryCodes: 'LI', location: 'Vaduz' },
  { value: 'Europe/Vatican', countryCodes: 'VA', location: 'Vatican' },
  { value: 'Europe/Vienna', countryCodes: 'AT', location: 'Vienna' },
  { value: 'Europe/Vilnius', countryCodes: 'LT', location: 'Vilnius' },
  { value: 'Europe/Volgograd', countryCodes: 'RU', location: 'Volgograd' },
  { value: 'Europe/Warsaw', countryCodes: 'PL', location: 'Warsaw' },
  { value: 'Europe/Zagreb', countryCodes: 'HR', location: 'Zagreb' },
  { value: 'Europe/Zurich', countryCodes: 'CH', location: 'Zurich' },
  { value: 'Indian/Antananarivo', countryCodes: 'MG', location: 'Antananarivo' },
  { value: 'Indian/Chagos', countryCodes: 'IO', location: 'Chagos' },
  { value: 'Indian/Christmas', countryCodes: 'CX', location: 'Christmas' },
  { value: 'Indian/Cocos', countryCodes: 'CC', location: 'Cocos' },
  { value: 'Indian/Comoro', countryCodes: 'KM', location: 'Comoro' },
  { value: 'Indian/Kerguelen', countryCodes: 'TF', location: 'Kerguelen' },
  { value: 'Indian/Mahe', countryCodes: 'SC', location: 'Mahe' },
  { value: 'Indian/Maldives', countryCodes: 'MV', location: 'Maldives' },
  { value: 'Indian/Mauritius', countryCodes: 'MU', location: 'Mauritius' },
  { value: 'Indian/Mayotte', countryCodes: 'YT', location: 'Mayotte' },
  { value: 'Indian/Reunion', countryCodes: 'RE', location: 'Reunion' },
  { value: 'Pacific/Apia', countryCodes: 'WS', location: 'Apia' },
  { value: 'Pacific/Auckland', countryCodes: 'NZ', location: 'Auckland' },
  { value: 'Pacific/Bougainville', countryCodes: 'PG', location: 'Bougainville' },
  { value: 'Pacific/Chatham', countryCodes: 'NZ', location: 'Chatham' },
  { value: 'Pacific/Chuuk', countryCodes: 'FM', location: 'Chuuk' },
  { value: 'Pacific/Easter', countryCodes: 'CL', location: 'Easter' },
  { value: 'Pacific/Efate', countryCodes: 'VU', location: 'Efate' },
  { value: 'Pacific/Fakaofo', countryCodes: 'TK', location: 'Fakaofo' },
  { value: 'Pacific/Fiji', countryCodes: 'FJ', location: 'Fiji' },
  { value: 'Pacific/Funafuti', countryCodes: 'TV', location: 'Funafuti' },
  { value: 'Pacific/Galapagos', countryCodes: 'EC', location: 'Galapagos' },
  { value: 'Pacific/Gambier', countryCodes: 'PF', location: 'Gambier' },
  { value: 'Pacific/Guadalcanal', countryCodes: 'SB', location: 'Guadalcanal' },
  { value: 'Pacific/Guam', countryCodes: 'GU', location: 'Guam' },
  { value: 'Pacific/Honolulu', countryCodes: 'US', location: 'Honolulu' },
  { value: 'Pacific/Kanton', countryCodes: 'KI', location: 'Kanton' },
  { value: 'Pacific/Kiritimati', countryCodes: 'KI', location: 'Kiritimati' },
  { value: 'Pacific/Kosrae', countryCodes: 'FM', location: 'Kosrae' },
  { value: 'Pacific/Kwajalein', countryCodes: 'MH', location: 'Kwajalein' },
  { value: 'Pacific/Majuro', countryCodes: 'MH', location: 'Majuro' },
  { value: 'Pacific/Marquesas', countryCodes: 'PF', location: 'Marquesas' },
  { value: 'Pacific/Midway', countryCodes: 'UM', location: 'Midway' },
  { value: 'Pacific/Nauru', countryCodes: 'NR', location: 'Nauru' },
  { value: 'Pacific/Niue', countryCodes: 'NU', location: 'Niue' },
  { value: 'Pacific/Norfolk', countryCodes: 'NF', location: 'Norfolk' },
  { value: 'Pacific/Noumea', countryCodes: 'NC', location: 'Noumea' },
  { value: 'Pacific/Pago_Pago', countryCodes: 'AS', location: 'Pago Pago' },
  { value: 'Pacific/Palau', countryCodes: 'PW', location: 'Palau' },
  { value: 'Pacific/Pitcairn', countryCodes: 'PN', location: 'Pitcairn' },
  { value: 'Pacific/Pohnpei', countryCodes: 'FM', location: 'Pohnpei' },
  { value: 'Pacific/Port_Moresby', countryCodes: 'PG', location: 'Port Moresby' },
  { value: 'Pacific/Rarotonga', countryCodes: 'CK', location: 'Rarotonga' },
  { value: 'Pacific/Saipan', countryCodes: 'MP', location: 'Saipan' },
  { value: 'Pacific/Tahiti', countryCodes: 'PF', location: 'Tahiti' },
  { value: 'Pacific/Tarawa', countryCodes: 'KI', location: 'Tarawa' },
  { value: 'Pacific/Tongatapu', countryCodes: 'TO', location: 'Tongatapu' },
  { value: 'Pacific/Wake', countryCodes: 'UM', location: 'Wake' },
  { value: 'Pacific/Wallis', countryCodes: 'WF', location: 'Wallis' },
];
